apiVersion: v1
kind: ServiceAccount
metadata:
  name: techeval-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: techeval-cluster-admin
subjects:
  - kind: ServiceAccount
    name: techeval-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
